### PR TITLE
Reduce bundle size

### PR DESCRIPTION
**Pull request by timedtext**
Importing in this way can reduce the bundle size when it is needed to package into a single file.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
@timedtext Do you have a link to any documentation regarding this?
Thinking about hunting down similar code in other Fastify repos.

**Comment by Uzlopak** [comment]
actually I dont like this, because it makes us dependent to know on the file structure of the dependencies.

**Comment by gurgunday** [comment]
Here's a place that partially talks about it: https://nodejs.org/api/packages.html#subpath-exports

Subpath exports can point to smaller .js files

A known example is `require('fs/promises')` vs `require('fs').promises`, the former can point to a file that only has the async functions thus reduce bundle size

**Comment by Uzlopak** [comment]
Problem is, that if the package itself changes its internal file structure, we would need to change the path in our files too.

**Comment by Fdawgs** [comment]
> Problem is, that if the package itself changes its internal file structure, we would need to change the path in our files too. 

Good point, maybe just the builtins like @gurgunday highlighted?

**Comment by Uzlopak** [comment]
builtins usually dont need to be bundled.

**Comment by timedtext** [comment]
> Problem is, that if the package itself changes its internal file structure, we would need to change the path in our files too.

Maybe we can write a unit test to make sure we can sync in time when the file structure changes.

**Pull request merged**
