### PR TITLE
test: test for array and regex origin options (#77)

### PR DESCRIPTION
**Pull request by alemagio**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add the `--100` flag to tap to verify it's 100% in Ci?

**Comment by alemagio** [comment]
Sure

**Comment by alemagio** [comment]
My bad actually, we have all line covered but not all branches.
If you don't mind I'll fix it asap.

**Comment by mcollina** [comment]
Landing this then

**Pull request merged**
