### PR TITLE
build(dependabot): ignore tap major updates

### PR DESCRIPTION
**Pull request by Fdawgs**
Example mass update PR for https://github.com/fastify/fastify/issues/5116

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
@fastify/plugins can run a mass update of tap and dependabot for all repos, which will save someone from having to do it manually as part of the v5 work.

**Comment by Uzlopak** [comment]
Is the answer from openjs or what it was regarding the use of tap as dev depency negative? 
I would like to have this clarified, before we restrict us.

**Comment by jsumners** [comment]
I would not hold my breath waiting on a licensing decision. It's going to take probably as long to get it as it will to prepare v5.

**Review by jsumners — APPROVED** [review]

**Comment by marco-ippolito** [comment]
they license has not been approved yet afaik, similar problem with npm in node
cc @mcollina

**Review by Eomm — APPROVED** [review]
I told to dependabot to ignore the dep by commenting the PRs in many repos TBH

PS: the pinned version does not have the new licence:
https://www.npmjs.com/package/tap/v/16.3.9

**Pull request merged**
