### PR TITLE
refactor(vary): use word character inside regex character class

### PR DESCRIPTION
**Pull request by Fdawgs**
- Replaced `a-zA-Z0-9_` inside character class with `\w` word character, [which is equivilent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Character_classes)
- Added the `u` unicode flag to every regex pattern, which [acts as a strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#description) for regex. See https://github.com/fastify/fastify-autoload/pull/330

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
Throw this into a draft for now. @Uzlopak noticed you've been making regex improvements in Node itself, do you know if using a `\w` character over `a-zA-Z0-9_` impacts performance at all?

**Comment by Uzlopak** [comment]
Tbh i never benched it. And i have no clue if it could have an impact. I mean theoretically \w gets just translated to  the specific chars internally. But maybe the regex engine optimizes it somehow.

But on the other hand i never used \w because like 10 years ato I always needed to lookup if i am not mistaking it with \W :))).

**Comment by Fdawgs** [comment]
Just used the benchmark in `benchmark/vary.js`

`master`:
image

`PR`:

image

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by gurgunday — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
