### PR TITLE
perf(index): use spread over `Object.assign()`

### PR DESCRIPTION
**Pull request by Fdawgs**
Nearly twice as fast, see https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#objectassign-vs-spread-operator

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Are not we in the small object case?

**Comment by Uzlopak** [comment]
Actually, it is not noticable for most cases. If you use a delegator, then you should notice.

**Comment by Fdawgs** [comment]
> 
> 
> Are not we in the small object case? 

Original code was creating a new object, so according to that table it was ~9m vs ~16m

**Comment by Fdawgs** [comment]
> Actually, it is not noticable for most cases. If you use a delegator, then you should notice.

Learnt something new today, thanks @Uzlopak!

**Comment by Uzlopak** [comment]
I wouldnt say that. Here in fastify-cors if you dont use that delegator style, than you will call that object merging only once. If you use delegator than it should be merging the object on every request. 

But there are potentially other repos where object merging happens on every request and not only on startup, where it is worth to investigate it further.

**Pull request merged**
